=== JpGeorgis/Projects/Daw/public/assets/mcq/quiz.dtd
<?xml version="1.0" encoding="utf-8" ?>
<!ELEMENT quiz (name|questions)*>
<!ELEMENT name (#PCDATA)>
<!ELEMENT questions (question)*>
<!ELEMENT question (text|answer)*>
<!ATTLIST question
    correct_answer CDATA #REQUIRED
        id CDATA #REQUIRED>
<!ELEMENT text (#PCDATA)>
<!ELEMENT answer (#PCDATA)>
<!ATTLIST answer
    id CDATA #REQUIRED>

=== JpGeorgis/Projects/Daw/public/assets/mcq/c3417921d5662a1902bd8842af5fe389.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE quiz SYSTEM "quiz.dtd">
<quiz>
    <name>Les grandes dates de la France</name>
    <questions>
        <question id="1" correct_answer="1">
            <text>Quelles sont les dates de la grande Guerre ?</text>
            <answer id="0">1939-1945</answer>
            <answer id="1">1914-1918</answer>
            <answer id="2">1969</answer>
        </question>
        <question id="2" correct_answer="0">
            <text>L'ONU a été crée en </text>
            <answer id="0">1945</answer>
            <answer id="1">1965</answer>
            <answer id="2">2002</answer>
        </question>
        <question id="3" correct_answer="2">
            <text>la Vᵉ République a été écrite en </text>
            <answer id="0">1946</answer>
            <answer id="1">1987</answer>
            <answer id="2">1958</answer>
        </question>
        <question id="4" correct_answer="0">
            <text>Le traité de Rome a été signé en </text>
            <answer id="0">1957</answer>
            <answer id="1">1967</answer>
            <answer id="2">1977</answer>
        </question>
        <question id="5" correct_answer="1">
            <text>Hitler s'est suicidé le </text>
            <answer id="0">30 mai 1945</answer>
            <answer id="1">30 avril 1945</answer>
            <answer id="2">10 avril 1945</answer>
        </question>
    </questions>
</quiz>

=== JpGeorgis/Projects/Daw/public/assets/mcq/9dc333e73d85f0a8c9e39edc23ac0930.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE quiz SYSTEM "quiz.dtd">
<quiz>
    <name>Questions générales</name>
    <questions>
        <question id="1" correct_answer="1">
            <text>De quoi est composée la matière ?</text>
            <answer id="0">De chips</answer>
            <answer id="1">D'Atomes</answer>
            <answer id="2">Le nombre 42</answer>
        </question>
        <question id="2" correct_answer="0">
            <text>Le poids s'exprime en..</text>
            <answer id="0">N</answer>
            <answer id="1">Kg</answer>
            <answer id="2">L</answer>
        </question>
        <question id="3" correct_answer="2">
            <text>La lune est un(e)...</text>
            <answer id="0">Etoile</answer>
            <answer id="1">Planète</answer>
            <answer id="2">Satellite</answer>
        </question>
        <question id="4" correct_answer="0">
            <text>Sur la Lune notre masse...</text>
            <answer id="0">Reste la même</answer>
            <answer id="1">Diminue</answer>
            <answer id="2">Augmente</answer>
        </question>
        <question id="5" correct_answer="1">
            <text>Sur la Lune notre poids...</text>
            <answer id="0">Reste le même</answer>
            <answer id="1">Diminue</answer>
            <answer id="2">Augmente</answer>
        </question>
    </questions>
</quiz>

=== JpGeorgis/Projects/Daw/public/assets/mcq/e38fb7d8d659220632421ab7000a4d9b.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE quiz SYSTEM "quiz.dtd">
<quiz>
    <name>Quelques capitales</name>
    <questions>
        <question id="1" correct_answer="1">
            <text>Quelle est la capitale de la France</text>
            <answer id="0">Bruxelles</answer>
            <answer id="1">Paris</answer>
            <answer id="2">Dijon</answer>
        </question>
        <question id="2" correct_answer="0">
            <text>La capitale du Venezuela est </text>
            <answer id="0">Caracas</answer>
            <answer id="1">Mexico</answer>
            <answer id="2">San Antonio</answer>
        </question>
        <question id="3" correct_answer="2">
            <text>Bogota est la capitale </text>
            <answer id="0">De la Russie</answer>
            <answer id="1">Du Mexique</answer>
            <answer id="2">De la Colombie</answer>
        </question>
        <question id="4" correct_answer="0">
            <text>La capitale de l'Australie est </text>
            <answer id="0">Canberra</answer>
            <answer id="1">Sidney</answer>
            <answer id="2">Melbourne</answer>
        </question>
        <question id="5" correct_answer="1">
            <text>La capitale de la Suisse est </text>
            <answer id="0">Zurich</answer>
            <answer id="1">Berne</answer>
            <answer id="2">Lausanne</answer>
        </question>
    </questions>
</quiz>

=== JpGeorgis/Projects/Daw/public/assets/mcq/76bdfde9714915b09f709ba66a7023bc.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE quiz SYSTEM "quiz.dtd">
<quiz>
    <name>Les bases de la biologie </name>
    <questions>
        <question id="1" correct_answer="1">
            <text>Que désigne la flore ?</text>
            <answer id="0">Les animaux</answer>
            <answer id="1">Les végétaux</answer>
            <answer id="2">Un peu de tout</answer>
        </question>
        <question id="2" correct_answer="0">
            <text>Au niveau d'observation moléculaire on trouve...</text>
            <answer id="0">L'ADN et l'ARN</answer>
            <answer id="1">Les organes</answer>
            <answer id="2">Les écosystèmes</answer>
        </question>
        <question id="3" correct_answer="2">
            <text>Un nom important de la biologie pourrait être... </text>
            <answer id="0">Emmanuel Macron</answer>
            <answer id="1">François Mitterrand</answer>
            <answer id="2">Jean-Baptiste Lamarck</answer>
        </question>
        <question id="4" correct_answer="0">
            <text>La trisomie la plus courante se situe sur les chromosomes... </text>
            <answer id="0">21</answer>
            <answer id="1">23</answer>
            <answer id="2">666</answer>
        </question>
        <question id="5" correct_answer="2">
            <text>Combien de chromosomes contient un caryotype humain ?</text>
            <answer id="0">21</answer>
            <answer id="1">22</answer>
            <answer id="2">23</answer>
        </question>
    </questions>
</quiz>

=== JpGeorgis/Projects/Daw/public/assets/mcq/c744451d030cfcf5805ed8eafe1c0148.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE quiz SYSTEM "quiz.dtd">
<quiz>
    <name>la chimie pour tous</name>
    <questions>
        <question id="1" correct_answer="1">
            <text>Les éléments sont regroupés dans... </text>
            <answer id="0">Une petite boite</answer>
            <answer id="1">Le tableau périodique des éléments</answer>
            <answer id="2">L'armoire qui mène à Narnia</answer>
        </question>
        <question id="2" correct_answer="0">
            <text>Que font les métaux alcalins au contact de l'eau ?</text>
            <answer id="0">Ils s'enflamment</answer>
            <answer id="1">Ils changent de couleur</answer>
            <answer id="2">Rien de particulier</answer>
        </question>
        <question id="3" correct_answer="2">
            <text>L'élement chimique de numéro atomique 1 est: </text>
            <answer id="0">Fer</answer>
            <answer id="1">Francium</answer>
            <answer id="2">Hydrogène</answer>
        </question>
        <question id="4" correct_answer="0">
            <text>Un atome ayant perdu un électron devient </text>
            <answer id="0">Un ion</answer>
            <answer id="1">Un demi atome</answer>
            <answer id="2">Obligatoirement radioactif</answer>
        </question>
        <question id="5" correct_answer="1">
            <text>Une solution avec un pH de 8 est...</text>
            <answer id="0">Neutre</answer>
            <answer id="1">Basique</answer>
            <answer id="2">Acide</answer>
        </question>
    </questions>
</quiz>

=== JpGeorgis/Projects/Daw/public/assets/mcq/893399d82d849485a2f19c0a39d2033a.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE quiz SYSTEM "quiz.dtd">
<quiz>
    <name>Les grands de la littérature</name>
    <questions>
        <question id="1" correct_answer="0">
            <text>On a transféré au Panthéon, en novembre 2002, les cendres de :</text>
            <answer id="0">Alexandre Dumas</answer>
            <answer id="1">Victor Hugo</answer>
            <answer id="2">George Sand</answer>
        </question>
        <question id="2" correct_answer="0">
            <text>Qui a écrit Madame Bovary </text>
            <answer id="0">Gustave Flaubert</answer>
            <answer id="1">Emile Zola</answer>
            <answer id="2">Victor Hugo</answer>
        </question>
        <question id="3" correct_answer="2">
            <text>Qu'a écrit Emile Zola </text>
            <answer id="0">Les misérables</answer>
            <answer id="1">Tartuffe</answer>
            <answer id="2">L'assommoir</answer>
        </question>
        <question id="4" correct_answer="0">
            <text>Qui a écrit le Discours de la méthode ? </text>
            <answer id="0">René Descartes</answer>
            <answer id="1">Marguerite Yourcenar</answer>
            <answer id="2">Emmanuel Kant</answer>
        </question>
        <question id="5" correct_answer="1">
            <text>Qui a écrit le Rouge et le Noir </text>
            <answer id="0">jean Paul Sartre</answer>
            <answer id="1">Stendhal</answer>
            <answer id="2">Hannah Arendt</answer>
        </question>
    </questions>
</quiz>
